version: "3.8"                              # 파일 규격 버전
services:                                   # 이 항목 밑에 실행하려는 컨테이너들을 정의
  open-run-app:
    image: shh0429/open-run-consumer
    container_name: open-run-consumer-app

    ports:
      - "80:8080"